on:
  pull_request:
    branches:
      - master
    paths:
      - '**.bicep'
name: Check correctness of bicep templates
jobs:
  lint:
    name: Check code syntax
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check ipgroups_max
        uses: ./.github/actions/ipgroups_max_bicep
        with:
          file_prefix: 'ipgroups'
          file_extension: 'bicep'
          max_ip_groups: '80'

      - name: Check CIDR prefix length
        uses: ./.github/actions/cidr_prefix_length_bicep
        with:
          file_prefixes: 'ipgroups rcg'
          file_extension: 'bicep'
          min_cidr_length: '24'
          base_dir: './'

      - name: Check Firewall rule priorities
        uses: ./.github/actions/fw_rule_prio_bicep
        with:
          file_prefixes: 'rcg'
          file_extension: 'bicep'
          min_prio: '10000'
          max_prio: '40000'
          base_dir: './'

      # Validate templates
      # Checkout remote repo for app04 (the path is important, the AzFW bicep template expects to find it there)
      - name: Checkout app04 repo
        uses: actions/checkout@v2
        with:
          repository: erjosito/segmentation-iac-app04
          ref: master
          path: './app04'
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        name: Run preflight validation
        with:
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./app01/bicep/infra-app01.bicep
          deploymentMode: Validate
      - uses: azure/arm-deploy@v1
        name: Run preflight validation
        with:
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./shared/bicep/azfwpolicy.bicep
          deploymentMode: Validate