on:
  push:
    branches: [master]
name: Azure ARM - Azure Firewall
jobs:
  deploy-azfw-policy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Deploy ARM template
    - name: Deploy ARM template for policy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/azfwpolicy.json
        parameters: policyName=TestPolicy
