on:
  push:
    branches: [master]
    paths:
      - '/app01/nsg*.bicep'
      - '/app01/infra*.bicep'
name: Azure bicep - Azure Firewall - On Push
jobs:
  deploy-app01:
    concurrency:
      group: deploy_app01
    runs-on: ubuntu-latest
    steps:
    # Checkout local repo
    - name: Checkout local repo
      uses: actions/checkout@main
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy bicep template
    - name: Deploy bicep template for global policy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./app01/bicep/infra-app01.bicep
        parameters: prefix=app01
