on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
name: Azure bicep - Azure Firewall - Triggered
jobs:
  deploy-azfw-policy:
    concurrency:
      group: deploy_azfw
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - name: Checkout local repo
      uses: actions/checkout@main
    # Checkout remote repo for app04 (the path is important, the bicep template expects to find it there)
    - name: Checkout app04 repo
      uses: actions/checkout@v2
      with:
        repository: erjosito/segmentation-iac-app04
        ref: master
        path: './app04'
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy bicep template
    - name: Deploy bicep template for global policy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./shared/bicep/azfwpolicy.bicep
        parameters: policyName=TestPolicyBicep deployVWAN=true
