on:
  push:
    branches: [master]
    paths:
      - '**/bicep/*.*'
name: Azure bicep - Azure Firewall - On Push
jobs:
  deploy-azfw-policy:
    concurrency:
      group: deploy_azfw
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - uses: actions/checkout@main
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy bicep template
    - name: Deploy bicep template for global policy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./shared/bicep/azfwpolicy.bicep
        parameters: policyName=TestPolicyBicep
