on:
  push:
    branches: [master]
    paths:
      - '**.json'
name: Azure ARM - Azure Firewall
jobs:
  deploy-azfw-policy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main
      # Define path filters
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          azfw_any:
            - 'AzFWPolicy/ARM/**'
          azfw_global:
            - 'AzFWPolicy/ARM/global/**.json'
          azfw_global_policy:
            - 'AzFWPolicy/ARM/global/azfwpolicy.json'
          azfw_global_rcg:
            - 'AzFWPolicy/ARM/global/rcg-global.json'
          azfw_global_ipgroups:
            - 'AzFWPolicy/ARM/global/ipgroups-global.json'
          azfw_app01:
          - 'AzFWPolicy/ARM/app01/**.json'
          azfw_app01_rcg:
            - 'AzFWPolicy/ARM/app01/rcg-app01.json'
          azfw_app01_ipgroups:
            - 'AzFWPolicy/ARM/app01/ipgroups-app01.json'
          azfw_app02:
            - 'AzFWPolicy/ARM/app02/**.json'
          azfw_app02_rcg:
            - 'AzFWPolicy/ARM/app02/rcg-app02.json'
          azfw_app02_ipgroups:
            - 'AzFWPolicy/ARM/app02/ipgroups-app02.json'
          azfw_app03:
            - 'AzFWPolicy/ARM/app03/**.json'
        # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy ARM templates for global resources
    - name: Deploy ARM template for global policy
      if: steps.filter.outputs.azfw_global_policy == 'true'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/global/azfwpolicy.json
        parameters: policyName=TestPolicy
    - name: Deploy ARM template for global IP groups
      if: steps.filter.outputs.azfw_global_ipgroups == 'true'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/global/ipgroups-global.json
    - name: Deploy ARM template for global RCG
      if: steps.filter.outputs.azfw_global_rcg == 'true'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/global/rcg-global.json
        parameters: policyName=TestPolicy rcgName=GlobalRCG
      # Deploy ARM templates for app01
    - name: Deploy ARM template for app01 IP groups
      if: steps.filter.outputs.azfw_app01_ipgroups == 'true'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/app01/ipgroups-app01.json
    - name: Deploy ARM template for app01 RCG
      if: steps.filter.outputs.azfw_app01_rcg == 'true'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/app01/rcg-app01.json
        parameters: policyName=TestPolicy rcgName=app01-RCG
    # Deploy ARM templates for app02
    - name: Deploy ARM template for app02 IP groups
      if: steps.filter.outputs.azfw_app02_ipgroups == 'true'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/app02/ipgroups-app02.json
    - name: Deploy ARM template for app02 RCG
      if: steps.filter.outputs.azfw_app02_rcg == 'true'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/app01/rcg-app02.json
        parameters: policyName=TestPolicy rcgName=app02-RCG
    # Deploy ARM templates for app03 (aggregate files)
    - name: Deploy ARM template for app03 rule collections (aggregate files)
      if: steps.filter.outputs.azfw_app03 == 'true'
      run: |
        python3 ./scripts/merge_rcg.py --directory ./AzFWPolicy/ARM/app03 --output-file ./AzFWPolicy/ARM/app03/rcg-merged.json --verbose
    - name: Deploy ARM template for merged app03 RCG
      if: steps.filter.outputs.azfw_app03 == 'true'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/app03/rcg-merged.json
        parameters: policyName=TestPolicy rcgName=app03-RCG
  