on:
  push:
    branches: [master]
    paths:
      - '**.json'
name: Azure ARM - Azure Firewall
jobs:
  deploy-azfw-policy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main
      # Define path filters
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          azfw_any:
            - 'AzFWPolicy/ARM/**.json'
          azfw_global:
            - 'AzFWPolicy/ARM/global/**.json'
          azfw_global_policy:
            - 'AzFWPolicy/ARM/global/azfwpolicy.json'
          azfw_global_rcg:
            - 'AzFWPolicy/ARM/global/rcg-global.json'
          azfw_global_ipgroups:
            - 'AzFWPolicy/ARM/global/ipgroups-global.json'
          azfw_app01:
          - 'AzFWPolicy/ARM/app01/**.json'
          azfw_app01_rcg:
            - 'AzFWPolicy/ARM/app01/rcg-app01.json'
          azfw_app01_ipgroups:
            - 'AzFWPolicy/ARM/app01/ipgroups-app01.json'
          azfw_app02:
            - 'AzFWPolicy/ARM/app02/**.json'
          azfw_app02_rcg:
            - 'AzFWPolicy/ARM/app02/rcg-app02.json'
          azfw_app02_ipgroups:
            - 'AzFWPolicy/ARM/app02/ipgroups-app02.json'
        # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Deploy ARM templates for global resources
    - name: Deploy ARM template for policy
      if: steps.filter.outputs.azfw_global_policy == 'true'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/global/azfwpolicy.json
        parameters: policyName=TestPolicy
    - name: Deploy ARM template for IP groups
      if: steps.filter.outputs.azfw_global_ipgroups == 'true'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/global/ipgroups-global.json
    - name: Deploy ARM template for RCG
      if: steps.filter.outputs.azfw_global_rcg == 'true'
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AzFWPolicy/ARM/global/rcg-global.json
        parameters: policyName=TestPolicy rcgName=GlobalRCG
  