on:
  push:
    branches: [master]
    paths:
      - 'app03/nsg*.bicep'
      - 'app03/infra*.bicep'
name: Azure bicep - Azure Firewall - On Push
jobs:
  deploy-app03-dev:
    concurrency:
      group: deploy_app03_dev
    runs-on: ubuntu-latest
    steps:
    # Checkout local repo
    - name: Checkout local repo
      uses: actions/checkout@main
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy bicep template
    - name: Deploy bicep template for global policy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./app03/dev/bicep/infra-app03.bicep
        parameters: prefix=app03dev
